setopt append_history
setopt extended_history
setopt hist_reduce_blanks
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_verify
setopt inc_append_history
setopt share_history
setopt IGNORE_EOF

unsetopt beep
unsetopt correct_all
unsetopt correct

zmodload zsh/terminfo
