setopt append_history
setopt extended_history
setopt hist_reduce_blanks
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_verify
setopt inc_append_history
unsetopt sharehistory

unsetopt beep
unsetopt correct
unsetopt correct_all
unsetopt interactive_comments

zmodload zsh/terminfo
